export const GET_UNITS = "GET_UNITS";
export const GET_UNITS_SUCCESS = "GET_UNITS_SUCCESS";
export const GET_UNITS_FAIL = "GET_UNITS_FAIL";

export const GET_UNIT_DETAILS = "GET_UNIT_DETAILS";
export const GET_UNIT_DETAILS_SUCCESS = "GET_UNIT_DETAILS_SUCCESS";
export const GET_UNIT_DETAILS_FAIL = "GET_UNIT_DETAILS_FAIL";

export const FILTER_BY_AGE = "FILTER_BY_AGE";
export const FILTER_BY_WOOD = "FILTER_BY_WOOD";
export const FILTER_BY_FOOD = "FILTER_BY_FOOD";
export const FILTER_BY_GOLD = "FILTER_BY_GOLD";