export const GET_UNITS = "GET_UNITS";
export const GET_UNITS_SUCCESS = "GET_UNITS_SUCCESS";
export const GET_UNITS_FAIL = "GET_UNITS_FAIL";

export const GET_UNIT_DETAILS = "GET_UNIT_DETAILS";
export const GET_UNIT_DETAILS_SUCCESS = "GET_UNIT_DETAILS_SUCCESS";
export const GET_UNIT_DETAILS_FAIL = "GET_UNIT_DETAILS_FAIL";